version: '3.8'

services:
  goseccuredb:
    container_name: goseccuredb
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: goseccuredb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  goseccure-apache:
    container_name: goseccure-apache
    image: sample:8.0-apache
    build: .
    depends_on:
      - goseccuredb
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      # Add other environment variables as needed
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html  # Example of mounting a local directory into the container

volumes:
  db_data:
  
